Add MintMoreNativeToken and circulating_supply to MintNativeToken
iotaledger/cli-wallet pull request #147
Opened 2022-09-07 10:52 UTC by Thoralf-M

# Description of change

Add MintMoreNativeToken and circulating_supply to MintNativeToken

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Running both commands

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-09-08 14:09 UTC, Thoralf-M commented
Waiting for https://github.com/iotaledger/wallet.rs/pull/1418

2022-09-15 07:43 UTC, samuel-rufi requested changes

2022-09-15 07:43 UTC, samuel-rufi commented on documentation/docs/03_account.md
> +| `token_id` | ✘         | N/A     | "0x08860e1f3593ba86c597cf86f61d8b04d8a714c02c7c5da7132d45be9c2ce6445c0300000000" |
Maybe remove the "" ? Amount is of type String to and doesn't have the ""

2022-09-15 08:23 UTC, samuel-rufi approved these changes

2022-09-15 09:37 UTC, thibault-martinez approved these changes

2022-09-15 09:38 UTC, merged