Add participation commands
iotaledger/cli-wallet pull request #157
Opened 2022-11-22 09:15 UTC by thibault-martinez

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-11-28 15:08 UTC, Thoralf-M commented on src/command/account_manager.rs
> +            ClientOptions::new().with_node("http://localhost:14265")?, // .with_node_sync_disabled(),
```suggestion
            ClientOptions::new().with_node("http://localhost:14265")?, // .with_ignore_node_health(),
```

2022-11-28 15:08 UTC, thibault-martinez commented on src/command/account_manager.rs
> +            ClientOptions::new().with_node("http://localhost:14265")?, // .with_node_sync_disabled(),
Still commented or... ?

2022-11-28 15:11 UTC, Thoralf-M commented on src/command/account_manager.rs
> +            ClientOptions::new().with_node("http://localhost:14265")?, // .with_node_sync_disabled(),
No harm to leave it there, might be good to enable it at some point to quickly test something

2022-11-29 10:33 UTC, Thoralf-M requested changes
Missing AccountManager participation methods

2022-11-29 11:01 UTC, thibault-martinez commented
Can I do it in another PR ?

2022-11-29 11:19 UTC, Thoralf-M approved these changes
Not sure where it best fits, but it might be good to also put https://github.com/iota-community/treasury/blob/main/specifications/hornet-participation-plugin.md somewhere so one can read more about the details of it (maybe add it to the account manager methods in the other PR?)

2022-11-29 11:29 UTC, thibault-martinez commented
> Not sure where it best fits, but it might be good to also put https://github.com/iota-community/treasury/blob/main/specifications/hornet-participation-plugin.md somewhere so one can read more about the details of it (maybe add it to the account manager methods in the other PR?)

Will do

2022-11-29 11:29 UTC, merged