Remove $ from code block so that the copy feature can be used
iotaledger/cli-wallet pull request #165
Opened 2023-01-29 22:04 UTC by Dr-Electron

# Description of change

I removed the $ from the code blocks so that people can just copy & paste code blocks

## Type of change

- Documentation Fix

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2023-01-30 08:45 UTC, thibault-martinez requested changes
Conflicts

2023-01-30 08:53 UTC, Dr-Electron commented on documentation/docs/01_installation.md
> +git clone git clone https://github.com/iotaledger/cli-wallet -b develop
```suggestion
git clone https://github.com/iotaledger/cli-wallet -b develop
```

2023-01-30 09:16 UTC, aleksei-korolev commented
These aren't code blocks, these are system shell commands that are supposed to be run by a normal system user (without elevated rights). This is what `$` indicates, and as a nice side effect it prevents people from copying the command blindly :trollface:

2023-01-30 09:18 UTC, thibault-martinez commented
The presence of a `>` or a `$` in shell commands online is so widespread that I don't think it's an issue to have them tbh. But I don't really care if we remove them or not. You guys decide.

2023-02-06 09:10 UTC, Dr-Electron commented
I know the meaning of `>`and `$`. But I prefer it being easy to copy.
The ideal solution would be to exclude those special cars from the copied content but I didn't find a way to do that yet.
I know other docs that do that, but as I said, didn't find a way in Docusaurus yet...

2023-02-06 09:13 UTC, Dr-Electron commented
> These aren't code blocks, these are system shell commands that are supposed to be run by a normal system user (without elevated rights). This is what `$` indicates, and as a nice side effect it prevents people from copying the command blindly :trollface:

They are code blocks per definition tho :trollface: (The component is called code block).
And in an step-by-stepp guide it makes sense to me to just copy the content easily

2023-02-20 12:37 UTC, lucas-tortora commented
> These aren't code blocks, these are system shell commands that are supposed to be run by a normal system user (without elevated rights). This is what `$` indicates, and as a nice side effect it prevents people from copying the command blindly :trollface:

UX-wise it's a bit irritating to have the extra `$` when you copy something, more so when it doesn't really add anything to the command. In my experience, it's not really going to stop from running, you're just going to get a `$: command not found` response on the first run, hit the up arrow, delete the `$`, and hit enter again.

2023-02-20 15:57 UTC, Dr-Electron commented
Guess we can merge this then? 🤔 It's 2:2 tho :trollface:

2023-02-20 16:02 UTC, Thoralf-M approved these changes

2023-02-20 16:12 UTC, thibault-martinez approved these changes

2023-02-20 16:12 UTC, merged